version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
      MYSQL_DATABASE: articles
