# Use an official Python runtime as a parent image
FROM python:3.7.16

# Set environment variables (customize as needed)
ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE project.settings
ENV MYSQL_ROOT_PASSWORD=1234567
ENV MYSQL_DATABASE=articles

# tp timezone
RUN apt-get update \
    &&  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
RUN TZ=Asia/Taipei \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata 
	
# Create and set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Install MySQL client
RUN apt-get update && apt-get install -y mysql-client

# Create a new MySQL database and table with columns
RUN service mysql start && \
    mysql -e "CREATE DATABASE articles;" && \
    mysql articles -e "CREATE TABLE articles (
        date time Not Null,
        title varchar(500) Not Null,
        content longtext,
        tags json,
        primary key(date)
    );" && \
    service mysql stop
	
# Install Gunicorn
RUN pip install gunicorn

# Run database migrations
RUN python /app/manage.py migrate

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Define environment variable for Gunicorn
ENV DJANGO_SETTINGS_MODULE=project.settings


# Define the command to run your application
CMD ["gunicorn", "project.wsgi:application", "--bind", "0.0.0.0:8000"]


